### ISSUE TITLE
CasparCG Random Server Crashes

### ISSUE THREAD

**Issue by talbojon** [CasparCG/server#1240]
Hi, 

I'm using CasparCG Server v2.0.7.e9fc25a Stable Release and I'm getting random crashes.  I can't predict when they're going to happen and I can't replicate.  The symptom is the Server window has closed and the desktop clients are unable to communicate with the server.  I guess it falls over on average once every other week, but on occasion it's happened twice in a particular day...  I'd rather it didn't cough at all...  

The server it's being run on is stable, never falls over.  It's a Steatite, BBC-4U-Q170-I7-CP9, running x64 WES7.  Intel i7-6700K @4GHz. 16GB RAM.  Using Blackmagic Decklink Duo2 cards.  

I am getting a specific repeated error.  The examples ones below are what I've been able to locate in the logs (windows search is utter rubbish!), they're not indicative of the frequency the server has fallen over...:

[2019-09-10 07:09:56.602] [4548] [fatal]   #######################
 UNHANDLED EXCEPTION: 
Adress:6E703C00
Code:3221225477
Flag:0
Info:17FBFAB4
Continuing execution. 

[2019-09-10 21:22:34.999] [5260] [fatal]   #######################
UNHANDLED EXCEPTION: 
Adress:6E703C00
Code:3221225477
Flag:0
Info:12B8FAB4
Continuing execution. 
#######################

2019-11-06 16:45:37.939] [7552] [fatal]   #######################
 UNHANDLED EXCEPTION: 
Adress:6E703C00
Code:3221225477
Flag:0
Info:17FEFAB4
Continuing execution. 
#######################

I've attached the log file from today to show you what it's doing prior to collapse...

[caspar_2019-11-06.log](https://github.com/CasparCG/server/files/3816483/caspar_2019-11-06.log)

Windows event logs are typically useless...

Has anyone else seen this before and know what the cause is?

Please help...  Lost in Oxford!  :-)

**Comment by ronag** [comment]
I would recommend you upgrade to 2.2. We don't really spend more time on such an old version.

**Comment by talbojon** [comment]
Thanks for getting back to me Robert,

I thought 2.2 was a beta version so not “production ready”...! If it’s fine then I’ll investigate tomorrow. Does it come with an updated client as well?

Jon Talbot
Senior Broadcast Engineer
BBC Oxford

Sent from my iPhone

On 6 Nov 2019, at 23:48, Robert Nagy <notifications@github.com> wrote:

﻿

I would recommend you upgrade to 2.2. We don't really spend more time on such an old version.

**Comment by talbojon** [comment]
Plus, do you know what that error means? I’m curious in case it is driver/machine or OS related...

**Comment by ronag** [comment]
> I thought 2.2 was a beta version so not “production ready”...! 

We've been using it for over a year in production. Thought I would probably use master at this point since it contains some recent fixes.

> If it’s fine then I’ll investigate tomorrow. Does it come with an updated client as well?

No idea. I'm not that involved with the client.

**Comment by dimitry-ishenko** [comment]
@talbojon we've been running 2.2 on Ubuntu 18.04 for a while. Works mostly fine. Seems to be leaking memory if you leave a file playing on a loop for 24 hours.

There is no updated client.

**Comment by vimlesh1975** [comment]
This error Code:3221225477 has been resolved by two methods.
1. Remove system audio from config file.
[https://casparcgforum.org/t/solved-server-wont-start/1990](url)

2. Put a reachable dns in network address.
[https://casparcgforum.org/t/caspar-2-07-shutdown/2002](url)

**Comment by PeterAkakpo** [comment]
Setting a reachable DNS does not resolve the issue when u are not connected
to the internet

**Comment by talbojon** [comment]
> 
> 
> I would recommend you upgrade to 2.2. We don't really spend more time on such an old version.

Hi, 

I've found 2.1 Beta 2 from the sourceforge repository...  Is that what you mean?  

> 
> 
> @talbojon we've been running 2.2 on Ubuntu 18.04 for a while. Works mostly fine. Seems to be leaking memory if you leave a file playing on a loop for 24 hours.
> 
> There is no updated client.

Where do I download 2.2 from?

Thanks everyone for your responses.  I'm going to play with v2.1/2.2 and see how that behaves.  I'll be back in contact if I have any more issues.  :-D

**Comment by ronag** [comment]
@dotarmin Where do we download the latest version from? The website seems to be quite out of date.

**Comment by ronag** [comment]
@talbojon I found this http://builds.casparcg.com/

**Comment by dotarmin** [comment]
@ronag, the same place you have used before: http://builds.casparcg.com/ :)

**Comment by ronag** [comment]
@dotarmin The "downloads" link on casparcg.com maybe needs a little love? :)

**Comment by dotarmin** [comment]
> The "downloads" link on casparcg.com maybe needs a little love? :)

Little is gentle hehe. I made an effort but the design wasn't liked and after that I haven't been having time. I can put it in the pipeline.

**Comment by talbojon** [comment]
I am having problems with the new version...

Are there stark differences between the caspar.config functionality of v2.0.7 and 2.2?  My problem is getting the client to see the "new" server...

I've attempted to reuse my 2.0.7 file, but didn't work.  I transferred the code in carefully, replicating the file structure that's in the new one, didn't work...  I've been fiddling around for ages and not getting anywhere...  Plus, I've set the logging to debug and I'm not getting anything out of it.  I can't find any documentation to help me understand what I'm doing...

It gets this far then stops running through start up...:

Type "q" to close application.
Logging [debug] or higher severity to log\/

[2019-11-07 14:46:55.499] [warning] Element thumbnails-path in casparcg.config has been deprecated. Use thumbnail-path i
nstead.
[2019-11-07 14:46:55.521] [info]    ############################################################################
[2019-11-07 14:46:55.521] [info]    CasparCG Server is distributed by the Swedish Broadcasting Corporation (SVT)
[2019-11-07 14:46:55.521] [info]    under the GNU General Public License GPLv3 or higher.
[2019-11-07 14:46:55.521] [info]    Please see LICENSE.TXT for details.
[2019-11-07 14:46:55.521] [info]    http://www.casparcg.com/
[2019-11-07 14:46:55.521] [info]    ############################################################################
[2019-11-07 14:46:55.521] [info]    Starting CasparCG Video and Graphics Playout Server 2.3.0 66b3508d Dev
[2019-11-07 14:46:55.528] [info]    Initialized ffmpeg module.
[2019-11-07 14:46:55.528] [info]    Initialized oal module.
[2019-11-07 14:46:55.528] [info]    Initialized decklink module.
[2019-11-07 14:46:55.528] [info]    Initialized screen module.
[2019-11-07 14:46:55.528] [info]    Initialized newtek module.
[2019-11-07 14:46:55.655] [info]    Initialized html module.
[2019-11-07 14:46:55.777] [info]    Initialized flash module.
[2019-11-07 14:46:55.780] [info]    Initialized bluefish module.
[2019-11-07 14:46:55.780] [info]    Initialized image module.
[2019-11-07 14:46:55.780] [info]    "D:/software\casparcg\casparcg-server2.2\casparcg.config":
[2019-11-07 14:46:55.780] [info]    -----------------------------------------
[2019-11-07 14:46:55.780] [info]    <?xml version="1.0" encoding="utf-8"?>
[2019-11-07 14:46:55.780] [info]    <configuration>
[2019-11-07 14:46:55.780] [info]       <paths>
[2019-11-07 14:46:55.780] [info]          <media-path>D:\GalVideo\</media-path>
[2019-11-07 14:46:55.780] [info]          <log-path>log\</log-path>
[2019-11-07 14:46:55.780] [info]          <data-path>data\</data-path>
[2019-11-07 14:46:55.780] [info]          <template-path>templates\</template-path>
[2019-11-07 14:46:55.780] [info]          <thumbnails-path>thumbnails\</thumbnails-path>
[2019-11-07 14:46:55.780] [info]       </paths>
[2019-11-07 14:46:55.780] [info]       <channels>
[2019-11-07 14:46:55.780] [info]          <channel>
[2019-11-07 14:46:55.780] [info]             <video-mode>PAL</video-mode>
[2019-11-07 14:46:55.780] [info]             <consumers>
[2019-11-07 14:46:55.780] [info]                <decklink>
[2019-11-07 14:46:55.780] [info]                   <device>1</device>
[2019-11-07 14:46:55.780] [info]                   <embedded-audio>true</embedded-audio>
[2019-11-07 14:46:55.780] [info]                </decklink>
[2019-11-07 14:46:55.780] [info]                <screen>
[2019-11-07 14:46:55.780] [info]                   <device>1</device>
[2019-11-07 14:46:55.780] [info]                </screen>
[2019-11-07 14:46:55.780] [info]                <system-audio/>
[2019-11-07 14:46:55.780] [info]             </consumers>
[2019-11-07 14:46:55.780] [info]          </channel>
[2019-11-07 14:46:55.780] [info]          <channel>
[2019-11-07 14:46:55.780] [info]             <video-mode>PAL</video-mode>
[2019-11-07 14:46:55.780] [info]             <consumers>
[2019-11-07 14:46:55.780] [info]                <decklink>
[2019-11-07 14:46:55.780] [info]                   <device>2</device>
[2019-11-07 14:46:55.780] [info]                   <embedded-audio>true</embedded-audio>
[2019-11-07 14:46:55.780] [info]                </decklink>
[2019-11-07 14:46:55.780] [info]                <screen>
[2019-11-07 14:46:55.780] [info]                   <device>1</device>
[2019-11-07 14:46:55.780] [info]                </screen>
[2019-11-07 14:46:55.780] [info]                <system-audio/>
[2019-11-07 14:46:55.780] [info]             </consumers>
[2019-11-07 14:46:55.780] [info]          </channel>
[2019-11-07 14:46:55.780] [info]       </channels>
[2019-11-07 14:46:55.780] [info]       <controllers>
[2019-11-07 14:46:55.780] [info]          <tcp>
[2019-11-07 14:46:55.780] [info]             <port>5250</port>
[2019-11-07 14:46:55.780] [info]             <protocol>AMCP</protocol>
[2019-11-07 14:46:55.780] [info]          </tcp>
[2019-11-07 14:46:55.780] [info]       </controllers>
[2019-11-07 14:46:55.780] [info]       <log-level>debug</log-level>
[2019-11-07 14:46:55.780] [info]    </configuration>
[2019-11-07 14:46:55.780] [info]    -----------------------------------------
[2019-11-07 14:46:56.865] [info]    Initializing OpenGL Device.
[2019-11-07 14:46:56.869] [info]    Initialized OpenGL 4.5.0 NVIDIA 392.00 NVIDIA Corporation
[2019-11-07 14:46:56.917] [info]    Initialized OpenGL Accelerated GPU Image Mixer for channel 1
[2019-11-07 14:46:56.918] [info]    video_channel[1|PAL] Successfully Initialized.
[2019-11-07 14:46:56.919] [info]    Initialized OpenGL Accelerated GPU Image Mixer for channel 2
[2019-11-07 14:46:56.920] [info]    video_channel[2|PAL] Successfully Initialized.
[2019-11-07 14:46:56.968] [info]    DeckLink Duo 2 [1-1|PAL] Enabled embedded-audio.
[2019-11-07 14:46:56.968] [info]    DeckLink Duo 2 [1-1|PAL] Disabled low-latency mode.
[2019-11-07 14:46:56.968] [info]    DeckLink Duo 2 [1-1|PAL] Enabled external keyer.
[2019-11-07 14:46:56.984] [info]    DeckLink Duo 2 [1-1|PAL] Initialized.
[2019-11-07 14:46:56.988] [info]    Screen consumer [1|PAL] Initialized.
[2019-11-07 14:46:57.030] [info]    oal[1|PAL] Initialized.
[2019-11-07 14:46:57.047] [info]    DeckLink Duo 2 [1-1|PAL] Reference signal: not detected.
[2019-11-07 14:46:57.127] [info]    DeckLink Duo 2 [2-2|PAL] Enabled embedded-audio.
[2019-11-07 14:46:57.127] [info]    DeckLink Duo 2 [2-2|PAL] Disabled low-latency mode.
[2019-11-07 14:46:57.127] [info]    DeckLink Duo 2 [2-2|PAL] Enabled external keyer.
[2019-11-07 14:46:57.136] [info]    DeckLink Duo 2 [2-2|PAL] Initialized.
[2019-11-07 14:46:57.207] [info]    DeckLink Duo 2 [2-2|PAL] Reference signal: not detected.
[2019-11-07 14:46:57.241] [info]    Screen consumer [2|PAL] Initialized.
[2019-11-07 14:46:57.244] [info]    oal[2|PAL] Initialized.
[2019-11-07 14:46:57.244] [info]    Initialized channels.
[2019-11-07 14:46:57.250] [info]    Initialized controllers.
[2019-11-07 14:46:57.250] [info]    Initialized osc.
[2019-11-07 14:46:58.247] [info]    DeckLink Duo 2 [1-1|PAL] Reference signal: locked.
[2019-11-07 14:46:58.407] [info]    DeckLink Duo 2 [2-2|PAL] Reference signal: locked.

**Comment by dotarmin** [comment]
Hi @talbojon 

Have you started `scanner.exe`?

**Comment by talbojon** [comment]
Ummm, I'd seen it in the folder, and didn't know that's required for operation.  Ok, will have a go!  

Thanks.

**Comment by dotarmin** [comment]
Issue can be opened if same is experienced in >= v2.2.x
