### ISSUE TITLE
COMMIT COMMAND NOT CLEAR DEFER COMMAND

### ISSUE THREAD

**Issue by DogLorenzo** [CasparCG/server#1503]
After I execute a COMMIT command for execute more animations, i have the same animations again if i resend COMMIT command.

The command doesn't clear the DEFER in the animations executed.

**Comment by Julusian** [comment]
This is fixed in the next build of master 7cbc4a4

**Comment by fillandkey** [comment]
Hi, Julusian.
I tried the new build but the issue is still present
