### ISSUE TITLE
Can't add more than one fullscreen Screen Consumer

### ISSUE THREAD

**Issue by CasparCGImport** [CasparCG/Server#3]
Converted from [SourceForge issue 3529444](http://sourceforge.net/support/tracker.php?aid=3529444), submitted by hummelstrand

I cannot get Caspar CG to output more than 1 screen consumer.  This issue came about when I was playing with key channel. ([url=http://casparcg.com/forum/viewtopic.php?f=6&t=661]Previous Conversations[/url]).

Robert suggested that in the config file, the following should work fine:

<consumers>
   <screen>
      <device>1</device>  
   </screen>
   <screen>
      <device>2</device>  
   </screen>
</consumers>

CasparCG seems to only pay attention to the second entry, in this case device two.

Robert's suggested work-a-round successfully adds new screens, but windowed:
ADD 1-1 SCREEN DEVICE 1

From: http://casparcg.com/forum/posting.php?mode=edit&f=10&p=3445

**Comment by dotarmin** [comment]
Fixed!

**Comment by fusionstream** [comment]
Sorry but how is this fixed?

I'm new to Caspar CG so maybe I misunderstood the OP. Is his goal to add multiple screen consumers in order to have duplicate screens per channel?

This still doesn't seem to work via casparcg.config but works via commands. Using different devices does work but is it possible to duplicate it while using the same device?

**Comment by hreinnbeck** [comment]
It would help if you'd post your config.  Have you checked if your config is valid? https://casparcg.net/validator/

**Comment by fusionstream** [comment]
The validator is new to me but it does pass though there seems to be an error with the validator as it says 2 channels instead of 2 screen consumers.

Here is my config. The goal is to have 2 screens on the same channel on the same device. I think this is what the OP already asked?

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <paths>
        <media-path>media/</media-path>
        <log-path>log/</log-path>
        <data-path>data/</data-path>
        <template-path>template/</template-path>
    </paths>
    <lock-clear-phrase>secret</lock-clear-phrase>
    <channels>
        <channel>
            <video-mode>720p6000</video-mode>
            <consumers>
                <screen>
                    <windowed>true</windowed>
                    <borderless>true</borderless>
                    <name>test 2</name>
                    <device>1</device>
                </screen>
                
                
                <system-audio />
            </consumers>
        </channel>
    </channels>
    <controllers>
        <tcp>
            <port>5250</port>
            <protocol>AMCP</protocol>
        </tcp>
    </controllers>
    <amcp>
        <media-server>
            <host>localhost</host>
            <port>8000</port>
        </media-server>
    </amcp>
</configuration>
`
