### ISSUE TITLE
Screen Consumer Uninitializing Hanging

### ISSUE THREAD

**Issue by grahamspr86** [CasparCG/server#932]
CasparCG Server 2.2.0 seems to hang when Uninitializing the Screen Consumer on QUIT after the build on the 12th March at 12:08, previous builds do not seem to be affected.

The last build to work is casparcg-server-87f7f19518a4ff5abf8d912ad60b49763f06f459-windows.zip

The Screen Consumer window does not close, it sits saying  video_channel[1|720p5000] Uninitializing.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <paths>
    <media-path>media/</media-path>
    <log-path>log/</log-path>
    <data-path>data/</data-path>
    <template-path>template/</template-path>
    <font-path>font/</font-path>
  </paths>
  <lock-clear-phrase>secret</lock-clear-phrase>
  <channels>
    <channel>
      <video-mode>720p5000</video-mode>
      <consumers>
        <screen>
          <device>0</device>
          <name>Screen Consumer Channel One</name>
        </screen>
        <system-audio/>
      </consumers>
    </channel>
  </channels>
  <controllers>
    <tcp>
      <port>5250</port>
      <protocol>AMCP</protocol>
    </tcp>
  </controllers>
  <amcp>
    <media-server>
      <host>localhost</host>
      <port>8000</port>
    </media-server>
  </amcp>
</configuration>
```

**Comment by TomKaltz** [comment]
I have seen this but couldn't reproduce again.

**Comment by jamesdwise** [comment]
I too have seen this, it is not 100% of the time but pretty often. 
sadly can't help with specific condition to reproduce it.....yet

**Comment by grahamspr86** [comment]
I appear to have it on two systems, Windows 7 and 10, happens every time.

**Comment by ronag** [comment]
This was fixed in the build after this one f2afe4dbabc99a03a23d89027d7e6d33da905d46

**Comment by grahamspr86** [comment]
I'll have to disagree it's still not working in the latest one today bb01003

![casparcgbb010037](https://user-images.githubusercontent.com/37407811/37512350-d248135c-28f9-11e8-9e7a-b6f6d36036af.png)

**Comment by ronag** [comment]
Ok. Now it is fixed in master. :)
